output_dir: "data/wallet_analysis"

browser_config:
  headless: True
  disable_security: True

browser_context_config:
  no_viewport: False
  browser_window_size:
    width: 1920
    height: 1080

agent_config:
  model_id: "gpt-4o"
  description: "Ethereum wallet analysis expert"
  instructions:
    - "Analyze Ethereum wallet data from Etherscan"
    - "Provide detailed analysis of wallet behavior and patterns"
    - "Ensure all calculations are accurate and well-documented"
